# Generated by Django 4.0.5 on 2022-06-04 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_product_product_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
