# Generated by Django 4.0.5 on 2022-06-05 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_whislist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Whislist',
            new_name='Wishlist',
        ),
    ]
